name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Save today's weather condition
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          pwd
          ls
          git status
          FILE=./docs/assets/data/`date +"%Y%m%d"`.json
          if [ -f "$FILE" ]; then
              echo "$FILE exists. Done for today."
          else
              echo "Begin to get today's weather condition."
              url="http://api.openweathermap.org/data/2.5/weather?id=4862034&units=metric&APPID="$API_KEY
              response=$(curl -f "$url")
              status=$?
              if [ $status -eq 0 ]; then
                  echo $response > $FILE
                  echo "$FILE saved."
                  echo `date +"%Y%m%d"` >> ./docs/assets/data.txt
              else
                  echo "curl exit code: ($status) $response"
                  exit $status
              fi
          fi
      - name: git check in
        run: |
          git config user.email "changhuixu@hotmail.com"
          git config user.name "Changhui Xu"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -a -m "add weather data"
            git push
          else
            echo 'unable to detech changes'
          fi
